---
layout: post
title: Radical Transformation
---
## Fragile beginning
I'm Nitin and I am frustrated with my life in all possible ways. I have decided to radically transform my life in next 6 months. I do not know how or what, but I am going to do it. I am going to write this book starting today of the journey that I take and where I land in next 6 months. It could very well be a failure but I am going to try. I can't live like this. I am also going to publish my daily notes and may be photos and videos of important milestones if I achieve any. I am going to be truthful and will write how I feel almost everyday and publish it, unedited. I am going to be standing naked, shamelessly in front of whoever reads this. I am done hiding behind my fake ego. I have nothing to hide now.
## My Today
I am a failure as a person. I am a failure in relationship, in material life and overall as a content person. I am insecure, I have no real friends and I have not achieved any goals I have set for myself materially.
I am almost 36 years old, married living in Hyderabad, India. I am 5'10" and 84 kg. I work in a decent company as a software engineer earning 3 lakh 10 thousand a month after taxes. My wife is loving, though we fight a lot. and by Indian standards, I, materially, seem to be in pretty good condition. But I am frustrated out of life.
## Frustration
I have lived half my lifespan already and so far I am running towards some material goals and that's how probably I might be spending rest of my life as well, running after goals and dying in pursuit, making some progress along the way. I have not done anything remarkable in my life. I am not proud of anything I have done. My goals and expectations were always so big that I have failed before I even begin. I am a wannabe in all aspects, whether relationship, job, physically. I have had always big goals and I have hardly done anything to achieve those goals. I have set goals many times in my life, some lofty goals and failed within a day or 2 of trying them. Some times I have went longer for some but failing them as well. Nothing works. I don't know what am I to do. I know what will lead to failure. Setting goals is one of them. But I know that I can't keep on living like this. I have to stop what I have been doing for last 36 years. That's not going to work. I know that I can't live without radically changing my life. Right now I am like a mouse running in a wheel getting nowhere. I have to get out.
